### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

### ISSUE THREAD

**Issue by bgeron** [SSLMate/ct-honeybee#3]
I have been getting the following output:

> [2017-10-17 16:46:05 +0200] ct-honeybee: Log error: ctlog.wosign.com: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
> [2017-10-17 16:46:07 +0200] ct-honeybee: Log error: ct.startssl.com: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

I'm running ct-honeybee using `python3 .../ct-honeybee`.

What would you recommend?

**Comment by AGWA** [comment]
Thanks for running ct-honeybee!  I just pushed a new version that fixes this (and also adds a bunch new logs to audit)

**Comment by bgeron** [comment]
Perfect, it works again! Thanks.
